@startuml
class Computer {
+ String cpu, ram, storage, screen
- Computer build()
}

class Builder {
- String cpu, ram, storage, screen
+ Builder buildCPU(String cpu)
+ Builder buildRAM(String ram)
+ Builder buildStorage(String storage)
+ Builder buildScreen(String screen)
+ Computer build()
}

Computer <.. Builder
@enduml